---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{rootGroup}}"
    mode: 0755
  loop: "{{ os_directories_to_create }}"

- name: Check for the initial reboot flag
  ansible.builtin.stat:
    path: /var/spool/initial.reboot.done
  register: initial_reboot_done

- include_tasks: linux.yml
  when: ansible_os_family not in ['FreeBSD']

- include_tasks: freebsd.yml
  when: ansible_os_family in ['FreeBSD']

- name: Deploy templates
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    decrypt: "{{item.decrypt}}"
  with_items:
    # rc.local is always in /etc on FreeBSD and Linux
    - { src: "rc.local.j2", dest: "/etc/rc.local", mode: "0755", owner: "root", group: "{{rootGroup}}", decrypt: "no" }
